version: '3.8'

services:
  quiz-bot:
    build: .
    container_name: telegram-quiz-bot
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Copy from .env file or set here
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - SESSION_SECRET=${SESSION_SECRET}
      - OWNER_ID=${OWNER_ID:-}
      - MODE=${MODE:-polling}
      - PORT=${PORT:-5000}
      # For webhook mode (uncomment and set):
      # - WEBHOOK_URL=https://your-domain.com/webhook
    volumes:
      # Persist database across container restarts
      - ./data:/app/data
      # Persist logs
      - ./bot.log:/app/bot.log
    env_file:
      - .env
    # Auto-restart on failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
